import { useState } from "react";
// import Developer from "./Components/Developer";
import Scroll from "./Components/Scroll";




const textToScroll = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin commodo tempor risus eu aliquam. Curabitur feugiat egestas enim id venenatis. Aenean dapibus sapien eget sem aliquam, at feugiat augue venenatis. Quisque in tortor ipsum. Donec sed ligula non orci tincidunt rutrum. Proin id est sit amet massa volutpat pulvinar. Suspendisse vel posuere nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ac elementum massa, fermentum blandit erat.

Maecenas ornare tincidunt sem sed hendrerit. Nunc sit amet diam tempor, fringilla diam volutpat, fringilla lorem. Morbi at euismod nunc. Etiam congue est nec ligula ultrices tincidunt. Integer sodales blandit varius. Nam mollis erat in lorem varius interdum. Maecenas nec dapibus lorem. Nullam dictum sem in risus dignissim luctus. Maecenas ut velit facilisis, finibus augue id, efficitur elit. In lacinia pharetra urna, nec pretium dui fermentum sit amet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce porta elit eget arcu feugiat malesuada.

Praesent lorem ante, consectetur ut blandit a, placerat vel ante. Cras vel metus viverra, dictum mi quis, posuere sem. Vestibulum vitae orci ut arcu ullamcorper luctus quis id ex. Mauris velit nisi, vulputate ut turpis id, tristique auctor tellus. Curabitur pulvinar, ipsum sit amet rutrum convallis, arcu nibh maximus dui, vitae gravida libero sem placerat tortor. Sed dictum efficitur ullamcorper. Vestibulum semper, mauris et tempus molestie, magna urna placerat tellus, et interdum purus elit euismod arcu. Nulla facilisi. Duis ipsum turpis, tincidunt at tellus ut, elementum blandit mauris. Nullam sit amet justo fringilla orci varius ultrices a ut urna. Proin lobortis arcu sed nunc mollis ornare. Sed sodales metus augue, quis rutrum ipsum egestas nec. Aliquam ac quam nunc. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Sed dapibus, massa a maximus luctus, quam ex varius ipsum, at rutrum lorem enim et sem. Pellentesque quis metus tortor. Pellentesque pellentesque nisi metus. Ut vel elit eu neque gravida tincidunt. Quisque sit amet lobortis ante, et maximus quam. Nam in augue at risus eleifend tincidunt. In hac habitasse platea dictumst. Aenean volutpat vitae lacus nec porttitor. Proin dapibus ante et libero aliquam, ac ornare libero pellentesque. Vivamus rhoncus, enim a iaculis tincidunt, ligula mi porta tellus, quis scelerisque est dolor quis nisi. Quisque cursus metus justo, ac sagittis velit porttitor vitae.

Cras varius interdum augue, at pharetra nibh pulvinar in. Pellentesque consectetur feugiat facilisis. Vestibulum rutrum viverra bibendum. Nunc ultrices justo eu nisi pretium sollicitudin. Pellentesque sollicitudin sapien in justo tempor, nec pharetra diam rutrum. Suspendisse vestibulum viverra varius. Donec molestie mauris vitae urna mollis, ut gravida eros commodo. Phasellus vulputate ligula nibh, non suscipit ante pretium at. Quisque sem arcu, tristique eget justo sed, pellentesque hendrerit nisl. In justo erat, scelerisque a nisi eget, ultricies mollis quam. Donec non massa at mauris semper lobortis sed eu sapien. Integer ac ultricies erat.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin commodo tempor risus eu aliquam. Curabitur feugiat egestas enim id venenatis. Aenean dapibus sapien eget sem aliquam, at feugiat augue venenatis. Quisque in tortor ipsum. Donec sed ligula non orci tincidunt rutrum. Proin id est sit amet massa volutpat pulvinar. Suspendisse vel posuere nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ac elementum massa, fermentum blandit erat.

Maecenas ornare tincidunt sem sed hendrerit. Nunc sit amet diam tempor, fringilla diam volutpat, fringilla lorem. Morbi at euismod nunc. Etiam congue est nec ligula ultrices tincidunt. Integer sodales blandit varius. Nam mollis erat in lorem varius interdum. Maecenas nec dapibus lorem. Nullam dictum sem in risus dignissim luctus. Maecenas ut velit facilisis, finibus augue id, efficitur elit. In lacinia pharetra urna, nec pretium dui fermentum sit amet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce porta elit eget arcu feugiat malesuada.

Praesent lorem ante, consectetur ut blandit a, placerat vel ante. Cras vel metus viverra, dictum mi quis, posuere sem. Vestibulum vitae orci ut arcu ullamcorper luctus quis id ex. Mauris velit nisi, vulputate ut turpis id, tristique auctor tellus. Curabitur pulvinar, ipsum sit amet rutrum convallis, arcu nibh maximus dui, vitae gravida libero sem placerat tortor. Sed dictum efficitur ullamcorper. Vestibulum semper, mauris et tempus molestie, magna urna placerat tellus, et interdum purus elit euismod arcu. Nulla facilisi. Duis ipsum turpis, tincidunt at tellus ut, elementum blandit mauris. Nullam sit amet justo fringilla orci varius ultrices a ut urna. Proin lobortis arcu sed nunc mollis ornare. Sed sodales metus augue, quis rutrum ipsum egestas nec. Aliquam ac quam nunc. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Sed dapibus, massa a maximus luctus, quam ex varius ipsum, at rutrum lorem enim et sem. Pellentesque quis metus tortor. Pellentesque pellentesque nisi metus. Ut vel elit eu neque gravida tincidunt. Quisque sit amet lobortis ante, et maximus quam. Nam in augue at risus eleifend tincidunt. In hac habitasse platea dictumst. Aenean volutpat vitae lacus nec porttitor. Proin dapibus ante et libero aliquam, ac ornare libero pellentesque. Vivamus rhoncus, enim a iaculis tincidunt, ligula mi porta tellus, quis scelerisque est dolor quis nisi. Quisque cursus metus justo, ac sagittis velit porttitor vitae.

Cras varius interdum augue, at pharetra nibh pulvinar in. Pellentesque consectetur feugiat facilisis. Vestibulum rutrum viverra bibendum. Nunc ultrices justo eu nisi pretium sollicitudin. Pellentesque sollicitudin sapien in justo tempor, nec pharetra diam rutrum. Suspendisse vestibulum viverra varius. Donec molestie mauris vitae urna mollis, ut gravida eros commodo. Phasellus vulputate ligula nibh, non suscipit ante pretium at. Quisque sem arcu, tristique eget justo sed, pellentesque hendrerit nisl. In justo erat, scelerisque a nisi eget, ultricies mollis quam. Donec non massa at mauris semper lobortis sed eu sapien. Integer ac ultricies erat.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin commodo tempor risus eu aliquam. Curabitur feugiat egestas enim id venenatis. Aenean dapibus sapien eget sem aliquam, at feugiat augue venenatis. Quisque in tortor ipsum. Donec sed ligula non orci tincidunt rutrum. Proin id est sit amet massa volutpat pulvinar. Suspendisse vel posuere nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ac elementum massa, fermentum blandit erat.

Maecenas ornare tincidunt sem sed hendrerit. Nunc sit amet diam tempor, fringilla diam volutpat, fringilla lorem. Morbi at euismod nunc. Etiam congue est nec ligula ultrices tincidunt. Integer sodales blandit varius. Nam mollis erat in lorem varius interdum. Maecenas nec dapibus lorem. Nullam dictum sem in risus dignissim luctus. Maecenas ut velit facilisis, finibus augue id, efficitur elit. In lacinia pharetra urna, nec pretium dui fermentum sit amet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce porta elit eget arcu feugiat malesuada.

Praesent lorem ante, consectetur ut blandit a, placerat vel ante. Cras vel metus viverra, dictum mi quis, posuere sem. Vestibulum vitae orci ut arcu ullamcorper luctus quis id ex. Mauris velit nisi, vulputate ut turpis id, tristique auctor tellus. Curabitur pulvinar, ipsum sit amet rutrum convallis, arcu nibh maximus dui, vitae gravida libero sem placerat tortor. Sed dictum efficitur ullamcorper. Vestibulum semper, mauris et tempus molestie, magna urna placerat tellus, et interdum purus elit euismod arcu. Nulla facilisi. Duis ipsum turpis, tincidunt at tellus ut, elementum blandit mauris. Nullam sit amet justo fringilla orci varius ultrices a ut urna. Proin lobortis arcu sed nunc mollis ornare. Sed sodales metus augue, quis rutrum ipsum egestas nec. Aliquam ac quam nunc. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Sed dapibus, massa a maximus luctus, quam ex varius ipsum, at rutrum lorem enim et sem. Pellentesque quis metus tortor. Pellentesque pellentesque nisi metus. Ut vel elit eu neque gravida tincidunt. Quisque sit amet lobortis ante, et maximus quam. Nam in augue at risus eleifend tincidunt. In hac habitasse platea dictumst. Aenean volutpat vitae lacus nec porttitor. Proin dapibus ante et libero aliquam, ac ornare libero pellentesque. Vivamus rhoncus, enim a iaculis tincidunt, ligula mi porta tellus, quis scelerisque est dolor quis nisi. Quisque cursus metus justo, ac sagittis velit porttitor vitae.

Cras varius interdum augue, at pharetra nibh pulvinar in. Pellentesque consectetur feugiat facilisis. Vestibulum rutrum viverra bibendum. Nunc ultrices justo eu nisi pretium sollicitudin. Pellentesque sollicitudin sapien in justo tempor, nec pharetra diam rutrum. Suspendisse vestibulum viverra varius. Donec molestie mauris vitae urna mollis, ut gravida eros commodo. Phasellus vulputate ligula nibh, non suscipit ante pretium at. Quisque sem arcu, tristique eget justo sed, pellentesque hendrerit nisl. In justo erat, scelerisque a nisi eget, ultricies mollis quam. Donec non massa at mauris semper lobortis sed eu sapien. Integer ac ultricies erat.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin commodo tempor risus eu aliquam. Curabitur feugiat egestas enim id venenatis. Aenean dapibus sapien eget sem aliquam, at feugiat augue venenatis. Quisque in tortor ipsum. Donec sed ligula non orci tincidunt rutrum. Proin id est sit amet massa volutpat pulvinar. Suspendisse vel posuere nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ac elementum massa, fermentum blandit erat.

Maecenas ornare tincidunt sem sed hendrerit. Nunc sit amet diam tempor, fringilla diam volutpat, fringilla lorem. Morbi at euismod nunc. Etiam congue est nec ligula ultrices tincidunt. Integer sodales blandit varius. Nam mollis erat in lorem varius interdum. Maecenas nec dapibus lorem. Nullam dictum sem in risus dignissim luctus. Maecenas ut velit facilisis, finibus augue id, efficitur elit. In lacinia pharetra urna, nec pretium dui fermentum sit amet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce porta elit eget arcu feugiat malesuada.

Praesent lorem ante, consectetur ut blandit a, placerat vel ante. Cras vel metus viverra, dictum mi quis, posuere sem. Vestibulum vitae orci ut arcu ullamcorper luctus quis id ex. Mauris velit nisi, vulputate ut turpis id, tristique auctor tellus. Curabitur pulvinar, ipsum sit amet rutrum convallis, arcu nibh maximus dui, vitae gravida libero sem placerat tortor. Sed dictum efficitur ullamcorper. Vestibulum semper, mauris et tempus molestie, magna urna placerat tellus, et interdum purus elit euismod arcu. Nulla facilisi. Duis ipsum turpis, tincidunt at tellus ut, elementum blandit mauris. Nullam sit amet justo fringilla orci varius ultrices a ut urna. Proin lobortis arcu sed nunc mollis ornare. Sed sodales metus augue, quis rutrum ipsum egestas nec. Aliquam ac quam nunc. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Sed dapibus, massa a maximus luctus, quam ex varius ipsum, at rutrum lorem enim et sem. Pellentesque quis metus tortor. Pellentesque pellentesque nisi metus. Ut vel elit eu neque gravida tincidunt. Quisque sit amet lobortis ante, et maximus quam. Nam in augue at risus eleifend tincidunt. In hac habitasse platea dictumst. Aenean volutpat vitae lacus nec porttitor. Proin dapibus ante et libero aliquam, ac ornare libero pellentesque. Vivamus rhoncus, enim a iaculis tincidunt, ligula mi porta tellus, quis scelerisque est dolor quis nisi. Quisque cursus metus justo, ac sagittis velit porttitor vitae.

Cras varius interdum augue, at pharetra nibh pulvinar in. Pellentesque consectetur feugiat facilisis. Vestibulum rutrum viverra bibendum. Nunc ultrices justo eu nisi pretium sollicitudin. Pellentesque sollicitudin sapien in justo tempor, nec pharetra diam rutrum. Suspendisse vestibulum viverra varius. Donec molestie mauris vitae urna mollis, ut gravida eros commodo. Phasellus vulputate ligula nibh, non suscipit ante pretium at. Quisque sem arcu, tristique eget justo sed, pellentesque hendrerit nisl. In justo erat, scelerisque a nisi eget, ultricies mollis quam. Donec non massa at mauris semper lobortis sed eu sapien. Integer ac ultricies erat.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin commodo tempor risus eu aliquam. Curabitur feugiat egestas enim id venenatis. Aenean dapibus sapien eget sem aliquam, at feugiat augue venenatis. Quisque in tortor ipsum. Donec sed ligula non orci tincidunt rutrum. Proin id est sit amet massa volutpat pulvinar. Suspendisse vel posuere nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ac elementum massa, fermentum blandit erat.

Maecenas ornare tincidunt sem sed hendrerit. Nunc sit amet diam tempor, fringilla diam volutpat, fringilla lorem. Morbi at euismod nunc. Etiam congue est nec ligula ultrices tincidunt. Integer sodales blandit varius. Nam mollis erat in lorem varius interdum. Maecenas nec dapibus lorem. Nullam dictum sem in risus dignissim luctus. Maecenas ut velit facilisis, finibus augue id, efficitur elit. In lacinia pharetra urna, nec pretium dui fermentum sit amet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce porta elit eget arcu feugiat malesuada.

Praesent lorem ante, consectetur ut blandit a, placerat vel ante. Cras vel metus viverra, dictum mi quis, posuere sem. Vestibulum vitae orci ut arcu ullamcorper luctus quis id ex. Mauris velit nisi, vulputate ut turpis id, tristique auctor tellus. Curabitur pulvinar, ipsum sit amet rutrum convallis, arcu nibh maximus dui, vitae gravida libero sem placerat tortor. Sed dictum efficitur ullamcorper. Vestibulum semper, mauris et tempus molestie, magna urna placerat tellus, et interdum purus elit euismod arcu. Nulla facilisi. Duis ipsum turpis, tincidunt at tellus ut, elementum blandit mauris. Nullam sit amet justo fringilla orci varius ultrices a ut urna. Proin lobortis arcu sed nunc mollis ornare. Sed sodales metus augue, quis rutrum ipsum egestas nec. Aliquam ac quam nunc. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Sed dapibus, massa a maximus luctus, quam ex varius ipsum, at rutrum lorem enim et sem. Pellentesque quis metus tortor. Pellentesque pellentesque nisi metus. Ut vel elit eu neque gravida tincidunt. Quisque sit amet lobortis ante, et maximus quam. Nam in augue at risus eleifend tincidunt. In hac habitasse platea dictumst. Aenean volutpat vitae lacus nec porttitor. Proin dapibus ante et libero aliquam, ac ornare libero pellentesque. Vivamus rhoncus, enim a iaculis tincidunt, ligula mi porta tellus, quis scelerisque est dolor quis nisi. Quisque cursus metus justo, ac sagittis velit porttitor vitae.

Cras varius interdum augue, at pharetra nibh pulvinar in. Pellentesque consectetur feugiat facilisis. Vestibulum rutrum viverra bibendum. Nunc ultrices justo eu nisi pretium sollicitudin. Pellentesque sollicitudin sapien in justo tempor, nec pharetra diam rutrum. Suspendisse vestibulum viverra varius. Donec molestie mauris vitae urna mollis, ut gravida eros commodo. Phasellus vulputate ligula nibh, non suscipit ante pretium at. Quisque sem arcu, tristique eget justo sed, pellentesque hendrerit nisl. In justo erat, scelerisque a nisi eget, ultricies mollis quam. Donec non massa at mauris semper lobortis sed eu sapien. Integer ac ultricies erat.

`;



export default function App() {
  // const [developer, setDeveloper] = useState({ name: "Pepe" });
  const [count, setCount] = useState(0);

  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
      {/* <Users /> */}
      {/* <TodoList /> */}
       <p>{textToScroll}</p>
      <Scroll />
      {/* <Developer developer={developer} /> */}
      <button onClick={() => setCount(count + 1)}>Contador: {count}</button>
    </div>
  );
}
